### ISSUE TITLE
Add Chrome Web Store link for the extension

### ISSUE THREAD

**Issue by Ashesh3** [besuper/TwitchNoSub#71]
**Describe the bug**
Hey, this works great for me. I decided to publish this to the chrome web store (Unlisted).

https://chrome.google.com/webstore/detail/twitchnosub/agoolijpgfbcenckfnjcpkccfcnomifg
 
You can match the source code of the extension and this GitHub repo. They are identical. Just putting it up here for anyone who wants to have it installed from the web store and not enable developer mode.

Author, feel free to request any changes to the listing or if you want it taken down. 

Thanks again for this project!

P.S: I have added a link to this repo as the homepage of the extension (it's still pending a review)

**Comment by HornWilly** [comment]
Need to update the code on chrome webstore.

Currently 0.7
https://github.com/besuper/TwitchNoSub/releases/tag/0.7

**Comment by Ashesh3** [comment]
> Need to update the code on chrome webstore.
> 
> Currently 0.7 [`0.7` (release)](https://github.com/besuper/TwitchNoSub/releases/tag/0.7)

Done, pending approval.

**Comment by Mishasama** [comment]
https://github.com/besuper/TwitchNoSub/releases/tag/0.7.1



> > Need to update the code on chrome webstore.
> > Currently 0.7 [`0.7` (release)](https://github.com/besuper/TwitchNoSub/releases/tag/0.7)
> 
> Done, pending approval.

It is still not updated.

**Comment by Ashesh3** [comment]
> [`0.7.1` (release)](https://github.com/besuper/TwitchNoSub/releases/tag/0.7.1)
> 
> > > Need to update the code on chrome webstore.
> > > Currently 0.7 [`0.7` (release)](https://github.com/besuper/TwitchNoSub/releases/tag/0.7)
> > 
> > 
> > Done, pending approval.
> 
> It is still not updated.

Update was rejected by Google reviewers.

**Comment by Mishasama** [comment]
> My recommendation is to delete it from the chrome web store, the only reason this still works is because its pretty unknown and small if many people start to use it and twitch notices they will block the way this extension bypasses their sub only view permissions.

Sorry... it's pretty well known. This script is not the only one that can be found and available on the Internet. I even suspect this is a marketing ploy by Amazon.
